version: "3"
services:
    nginx:
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - "3050:80"
    mongo:
        container_name: taskman_mongo
        image: mongo
        ports:
            - "27017:27017"
    client:
        build:
            context: ./taskman_website
            dockerfile: Dockerfile
        volumes:
            - /app/node_modules
            - ./taskman_website:/app
    api:
        build:
            context: ./taskman_backend
            dockerfile: Dockerfile
        ports:
            - "4000:4000"
            - "9229:9229"
        volumes:
            - /app/node_modules
            - ./taskman_backend:/app
        environment:
            - PORT=4000
            - NODE_ENV=development
            - JWT_SECRET=12345678
